const elementNames = {
  addContacts: "addContacts",
  allChats: "allChats",
  bot: "bot",
  calls: "calls",
  channels: "channels",
  contacts: "contacts",
  countryCode: "countryCode",
  countryName: "countryName",
  editChats: "editChats",
  firstName: "firstName",
  groups: "groups",
  lastName: "lastName",
  logout: "logout",
  menu: "menu",
  newChannel: "newChannel",
  newGroup: "newGroup",
  nightMode: "nightMode",
  personal: "personal",
  phoneNumber: "phoneNumber",
  search: "search",
  settings: "settings",
  unread: "unread",
  verificationCode: "verificationCode",
};

export { elementNames };
