const VIEW_MODES = {
  MESSENGER: "MESSENGER",
  NEW_USER_PROFILE: "NEW_USER_PROFILE",
  SIGN_IN: "SIGN_IN",
  VERIFY_SIGN_IN: "VERIFY_SIGN_IN",
};

const APP_DRAWER_ANCHORS = {
  bottom: "bottom",
  left: "left",
  right: "right",
  top: "top",
};

const PERSISTENT_STORAGE_KEYS = {
  MAIN_TOKEN: "MAIN_TOKEN",
  VERIFY_TOKEN: "VERIFY_TOKEN",
  STUFFS: "STUFFS",
};

export { PERSISTENT_STORAGE_KEYS, VIEW_MODES, APP_DRAWER_ANCHORS };
