const APP_DRAWER_ANCHORS = {
  bottom: "bottom",
  left: "left",
  right: "right",
  top: "top",
};

const GLOBAL_LOADING_TYPES = {
  OVERLAY: "OVERLAY",
  FULL_PAGE: "FULL_PAGE",
};

const PERSISTENT_STORAGE_KEYS = {
  MAIN_TOKEN: "MAIN_TOKEN",
  VERIFY_TOKEN: "VERIFY_TOKEN",
  STUFFS: "STUFFS",
};

const VIEW_MODES = {
  MESSENGER: "MESSENGER",
  NEW_USER_PROFILE: "NEW_USER_PROFILE",
  SIGN_IN: "SIGN_IN",
  VERIFY_SIGN_IN: "VERIFY_SIGN_IN",
  LOADING: "LOADING",
};

export {
  APP_DRAWER_ANCHORS,
  GLOBAL_LOADING_TYPES,
  PERSISTENT_STORAGE_KEYS,
  VIEW_MODES,
};
