//TODO: Update settings dialogs
const DIALOG_NAMES = {
  ADD_CONTACT: "addContact",
  CONTACTS: "contacts",
  USER_INFO: "userInfo",
};

const INITIAL_SETUP_STATUS = {
  DONE: "DONE",
  FAILED: "FAILED",
  NEVER: "NEVER",
  ON_PROGRESS: "ON_PROGRESS",
  PROGRESSING: "PROGRESSING",
};

const VIEW_MODES = {
  CHECK_CURRENT_USER: "CHECK_CURRENT_USER",
  INITIAL_SETUP: "INITIAL_SETUP",
  MESSENGER: "MESSENGER",
  CREATE_NEW_USER: "CREATE_NEW_USER",
  SIGN_IN: "SIGN_IN",
  VERIFY_SIGN_IN: "VERIFY_SIGN_IN",
};

const globalStatics = {
  DIALOG_NAMES,
  INITIAL_SETUP_STATUS,
  VIEW_MODES,
};

export { globalStatics };
