const GLOBAL_ACTION_TYPES = {
  APP_DRAWER_OPEN_CHANGE: "APP_DRAWER_OPEN_CHANGE",
  APP_PROGRESSION_CHANGE: "APP_PROGRESSION_CHANGE",
  CHANGE_INITIAL_SETUP_STATUS: "CHANGE_INITIAL_SETUP_STATUS",
  DIALOG_OPEN_STATE_CHANGE: "DIALOG_OPEN_STATE_CHANGE",
  GLOBAL_LOADING_OPEN_CHANGE: "GLOBAL_LOADING_OPEN_CHANGE",
  ONLINE_STATUS_CHANGE: "ONLINE_STATUS_CHANGE",
  RESET_GLOBAL_STATE: "RESET_GLOBAL_STATE",
  VIEW_MODE_ONCHANGE: "VIEW_MODE_ONCHANGE",
};

export { GLOBAL_ACTION_TYPES };
