const USER_ACTION_TYPES = {
  ADD_NEW_CONTACT: "ADD_NEW_CONTACT",
  RESET_USER_STATE: "RESET_USER_STATE",
  UPDATE_ALL_USER_DATA: "UPDATE_ALL_USER_DATA",
  UPDATE_USER_CONTACTS: "UPDATE_USER_CONTACTS",
};

export { USER_ACTION_TYPES };
