const AUTH_ACTION_TYPES = {
  COUNTRY_CODE_ONCHANGE: "COUNTRY_CODE_ONCHANGE",
  COUNTRY_NAME_ONCHANGE: "COUNTRY_NAME_ONCHANGE",
  FIRST_NAME_ONCHANGE: "FIRST_NAME_ONCHANGE",
  LAST_NAME_ONCHANGE: "LAST_NAME_ONCHANGE",
  PHONE_NUMBER_ONCHANGE: "PHONE_NUMBER_ONCHANGE",
  RESET_AUTH_STATE: "RESET_AUTH_STATE",
  SELECTED_COUNTRY_ONCHANGE: "SELECTED_COUNTRY_ONCHANGE",
  UPDATE_VERIFY_TOKEN: "UPDATE_VERIFY_TOKEN",
  VERIFICATION_CODE_ONCHANGE: "VERIFICATION_CODE_ONCHANGE",
};

export { AUTH_ACTION_TYPES };
