const MESSAGE_ACTION_TYPES = {
  ADD_NEW_MESSAGE: "ADD_NEW_MESSAGE",
  CLOSE_RIGHT_SIDE: "CLOSE_RIGHT_SIDE",
  CREATE_NEW_PRIVATE_CHAT: "CREATE_NEW_PRIVATE_CHAT",
  MESSAGE_INPUT_ONCHANGE: "MESSAGE_INPUT_ONCHANGE",
  NEW_PRIVATE_CHAT_MESSAGE: "NEW_PRIVATE_CHAT_MESSAGE",
  RESET_MESSAGE_STATE: "RESET_MESSAGE_STATE",
  SELECTED_USER_FOR_PRIVATE_CHAT: "SELECTED_USER_FOR_PRIVATE_CHAT",
  UPDATE_ALL_PRIVATE_CHATS: "UPDATE_ALL_PRIVATE_CHATS",
  UPDATE_ONE_PRIVATE_CHAT: "UPDATE_ONE_PRIVATE_CHAT",
};

export { MESSAGE_ACTION_TYPES };
