const MESSAGE_ACTION_TYPES = {
  ADD_NEW_MESSAGE: "ADD_NEW_MESSAGE",
  CLOSE_RIGHT_SIDE: "CLOSE_RIGHT_SIDE",
  MESSAGE_INPUT_ONCHANGE: "MESSAGE_INPUT_ONCHANGE",
  RESET_MESSAGE_STATE: "RESET_MESSAGE_STATE",
  SELECTED_USER_FOR_PRIVATE_CHAT: "SELECTED_USER_FOR_PRIVATE_CHAT",
  UPDATE_ALL_PRIVATE_CHATS: "UPDATE_ALL_PRIVATE_CHATS",
};

export { MESSAGE_ACTION_TYPES };
