const MESSAGE_ACTION_TYPES = {
  CLOSE_RIGHT_SIDE: "CLOSE_RIGHT_SIDE",
  MESSAGE_INPUT_ONCHANGE: "MESSAGE_INPUT_ONCHANGE",
  RESET_MESSAGE_STATE: "RESET_MESSAGE_STATE",
  SELECTED_USER_FOR_PRIVATE_CHAT: "SELECTED_USER_FOR_PRIVATE_CHAT",
  UPDATE_PRIVATE_CHAT_MESSAGES: "UPDATE_PRIVATE_CHAT_MESSAGES",
};

export { MESSAGE_ACTION_TYPES };
