const OTHER_ACTION_TYPES = {
  SET_COUNTRIES: "SET_COUNTRIES",
  RESET_OTHER_STATE: "RESET_OTHER_STATE",
  SET_WELCOME_MESSAGE: "SET_WELCOME_MESSAGE",
  IS_STUFF_IMPORTED: "IS_STUFF_IMPORTED",
};

export { OTHER_ACTION_TYPES };
