const VIEW_MODES = {
  MESSENGER: "MESSENGER",
  NEW_USER_PROFILE: "NEW_USER_PROFILE",
  SIGN_IN: "SIGN_IN",
  VERIFY_SIGN_IN: "VERIFY_SIGN_IN",
};

const PERSISTENT_STORAGE_KEYS = {
  MAIN_TOKEN: "MAIN_TOKEN",
  VERIFY_TOKEN: "VERIFY_TOKEN",
};

export { PERSISTENT_STORAGE_KEYS, VIEW_MODES };
